name: 'local_bike'
version: '1.0.0'
config-version: 2

profile: 'local_bike'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  gcp_project_id: "databird-489009"  # Nom du projet dans big query
  dataset_name: "raw_data_localbike"         #  Nom du dataset dans BigQuery

models:
  local_bike:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts